name: rowdy
description: A new Flutter project.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.12.0-0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  bloc: ^7.0.0-nullsafety.3
  cloud_firestore: ^1.0.1
  firebase_analytics: ^7.1.1
  firebase_auth: ^1.0.1
  firebase_core: ^1.0.1
  flutter_bloc: ^7.0.0-nullsafety.5
  flutter_launcher_icons: ^0.9.0
  freezed_annotation: ^0.14.0
  intl: ^0.17.0
  json_serializable: ^4.0.2
  shared_preferences: ^2.0.4
  timeago: ^3.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  bloc_test: 8.0.0-nullsafety.5
  build_runner: ^1.11.5
  freezed: ^0.14.0
  mocktail: 0.1.0
  very_good_analysis: ^2.0.0

flutter_icons:
  ios: true
  android: true
  image_path_ios: "assets/icon/icon_ios.png"
  image_path_android: "assets/icon/icon_android.png"

flutter:
  assets:
    - assets/images/
  uses-material-design: true
  generate: true

  fonts:
    - family: sficonsets
      fonts:
        - asset: packages/flutter_sfsymbols/fonts/sficonsets.ttf
